services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    mem_limit: 4g
    memswap_limit: 4g
    environment:
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_MAX_LOADED_MODELS=1
      - OLLAMA_KEEP_ALIVE=24h


  openwebui:
    image: ghcr.io/open-webui/open-webui
    container_name: openwebui
    restart: unless-stopped
    ports:
      - "3000:8080"
    mem_limit: 1g
    memswap_limit: 1g
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - CORS_ALLOW_ORIGIN=http://localhost:3000;https://q99q7gf9-3000.inc1.devtunnels.ms
      - FORWARDED_ALLOW_IPS='*'
      - OPENWEBUI_LOG_LEVEL=info
      - OPENWEBUI_SESSION_SECRET=supersecretkey
      - OPENWEBUI_RBAC_ENABLED=true
      - OPENWEBUI_AUTH_PROVIDER=local
      - OPENWEBUI_DEFAULT_ADMIN_USERNAME=admin
      - OPENWEBUI_DEFAULT_ADMIN_PASSWORD=ChangeMe123!
      - OPENWEBUI_SESSION_COOKIE_SAMESITE=None
      - OPENWEBUI_SESSION_COOKIE_SECURE=true
      - OPENWEBUI_SITE_URL=https://q99q7gf9-3000.inc1.devtunnels.ms
    depends_on:
      - ollama
    volumes:
      - openwebui_data:/app/backend/data

volumes:
  ollama_data:
  openwebui_data: